project:
  type: website
  output-dir: docs

website:
  title: "Jessica S. Guo"
  twitter-card:
    creator: "@JessicaSGuo"
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Data Science"
        href: ds.qmd
      - text: "Teaching"
        href: teaching.qmd

  page-footer:
    left: "© Copyright 2022 Jessica S. Guo"

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true

editor: visual

