project:
  type: website
  output-dir: docs

website:
  title: PEPPER Lab HMC
  description: The Plant & Ecosystem Physiology, Potential, and Environment - PEPPER - Lab at Harvey Mudd College - HMC 
  image: img/PEPPER-logo.png
  site-url: https://jessicaguo.github.io
  repo-url: https://github.com/jessicaguo/jessicaguo.github.io
  open-graph: true
  favicon: "img/PEPPER-logo.png"
  twitter-card:
    creator: "@JessicaSGuo"
  navbar:
    title: "&#8203;"
    background: "#676d02"
    logo: img/PEPPER-logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "People"
        href: people.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Publications"
        href: pubs.qmd

  page-footer:
    left: "© Copyright 2026 Jessica S. Guo"

format:
  html:
    theme: 
      [styles.css, journal]
      
    css: styles.css
    toc: false
    highlight-style: tango

editor: visual

