project:
  type: website
  output-dir: docs

website:
  title: "Jessica S. Guo"
  site-url: https://jessicaguo.github.io
  repo-url: https://github.com/jessicaguo/jessicaguo.github.io
  twitter-card:
    creator: "@JessicaSGuo"
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Data Science"
        href: ds.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Publications"
        href: pubs.qmd

  page-footer:
    left: "© Copyright 2022 Jessica S. Guo"

format:
  html:
    theme: 
      light: journal
      dark: minty
    css: styles.css
    toc: true
    highlight-style: tango

editor: visual

