---
title: "Publications"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
library(htmltools)
library(dplyr)
library(readr)
library(readxl)

# pub.data <- read_csv("data/academic_dataset.csv") |>
#   filter(status == "Published")

# pub.data <- read_excel("data-and-scripts/authorship-table-guo-2026-06-23.xls") |>
#   mutate(title = paste0(title, "."),
#          authors = paste0(authors, "."),
#          item_info = paste0(item_info, "."))

pub.data <- read.csv("data-and-scripts/api_authorship.csv")

years <- unique(pub.data$publishYear) |> sort(decreasing = T)
for(k in years){
  cat(paste0(h2(k)))
  
  pub.in <- pub.data |> 
    filter(publishYear == k) |> 
    arrange(types)
  
  for(type in unique(pub.in$types)){
    cat(paste0(h4(type)))
    
    pub.k <- pub.in |> filter(types == type)
    
     for(i in 1:nrow(pub.k)){
       cat(paste0(
         div(
          paste0(pub.k$authorsList[i], "."),
          paste0("(", pub.k$publishYear[i], "). "),
          tags$b(paste0(pub.k$title[i], ".")),
          tags$i(paste0(pub.k$sourceTitle[i], ".")),
          tags$a(pub.k$link[i], href = pub.k$link[i])
           )
         )
       )
     }
  }
  
  cat(paste0(br(), br()))
  }
```
